trigger:
- main

pool:
  name : default
  demands: 
  - agent.name -equals jesa-agent

variables:
  phpVersion: 8.2.27

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

# Run tests
- script: |
    vendor/bin/phpunit --coverage-text
  displayName: 'Run unit tests with PHPUnit'

# - script: |
#     docker build -t myapp:latest .
#   displayName: 'Build Docker image'
 

